ALTER TABLE [dbo].[Dsv]
    ADD CONSTRAINT [PK_Dsv] PRIMARY KEY CLUSTERED ([DsvID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

