ALTER TABLE [dbo].[Dsv]
    ADD CONSTRAINT [UQ_Dsv01] UNIQUE NONCLUSTERED ([DsvName] ASC, [DsvType] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

