CREATE QUEUE [dbo].[ETLController_Request_Queue] 
WITH STATUS = ON , RETENTION = OFF , ACTIVATION 
(  
	STATUS = ON , 
	PROCEDURE_NAME = [dbo].[prc_ProcessQueue] , 
	MAX_QUEUE_READERS = 32 , 
	EXECUTE AS N'dbo'  
), 
POISON_MESSAGE_HANDLING (STATUS = ON)
;