ALTER TABLE [dbo].[EventLog]
    ADD CONSTRAINT [PK_EventLog] PRIMARY KEY CLUSTERED ([EventTypeID] ASC, [EventID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

