/*
Deployment script for ETL_ControllerTest

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar ETL_ControllerCommon "ETL_ControllerCommon"
:setvar ETL_ControllerNode "ETL_ControllerNode"
:setvar DatabaseName "ETL_ControllerTest"
:setvar DefaultFilePrefix "ETL_ControllerTest"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL12.SQL14\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL12.SQL14\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'disable';


GO
/*
 Pre-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be executed before the build script.	
 Use SQLCMD syntax to include a file in the pre-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the pre-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
GO

GO
PRINT N'Dropping [dbo].[SystemParametersEnvironmentNameCK]...';


GO
ALTER TABLE [dbo].[SystemParameters] DROP CONSTRAINT [SystemParametersEnvironmentNameCK];


GO
PRINT N'Creating [dbo].[SystemParametersEnvironmentNameCK]...';


GO
ALTER TABLE [dbo].[SystemParameters] WITH NOCHECK
    ADD CONSTRAINT [SystemParametersEnvironmentNameCK] CHECK (EnvironmentName IN ('All', 'Dev', 'SIT', 'UAT', 'PROD'));


GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[SystemParameters] WITH CHECK CHECK CONSTRAINT [SystemParametersEnvironmentNameCK];


GO
PRINT N'Update complete.';


GO
