//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIAS.Framework.DeltaExtractor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIAS.Framework.DeltaExtractor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;xsd:schema xmlns=&quot;ETLController.XSD&quot;
        /// xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        /// targetNamespace=&quot;ETLController.XSD&quot;
        /// elementFormDefault=&quot;qualified&quot;&gt;
        ///
        ///  &lt;xsd:complexType name=&quot;Process&quot;&gt;
        ///    &lt;xsd:sequence&gt;
        ///      &lt;xsd:element name=&quot;Process&quot; type=&quot;xsd:string&quot; minOccurs=&quot;0&quot; maxOccurs=&quot;1&quot; /&gt;
        ///      &lt;xsd:element name=&quot;Param&quot; type=&quot;xsd:string&quot; minOccurs=&quot;0&quot; maxOccurs=&quot;1&quot; /&gt;
        ///    &lt;/xsd:sequence&gt;
        ///    &lt;xsd:attribute name=&quot;ProcessID&quot; type=&quot;xsd:int&quot; use=&quot;required&quot; /&gt;
        ///    &lt;xsd:attrib [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CDRXSD {
            get {
                return ResourceManager.GetString("CDRXSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsd:schema xmlns=&quot;DeltaExtractor.XSD&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;DeltaExtractor.XSD&quot;  elementFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;!-- Guid Pattern definition --&gt;
        ///	&lt;xsd:simpleType name=&quot;GUID&quot;&gt;
        ///		&lt;xsd:restriction base=&quot;xsd:string&quot;&gt;
        ///			&lt;xsd:pattern value=&quot;[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}&quot; /&gt;
        ///		&lt;/xsd:restriction&gt;
        ///	&lt;/xsd:simpleType&gt;
        ///	&lt;!-- List of possible actions --&gt;
        ///	&lt;xsd:simpleType name=&quot;Actions&quot;&gt;
        ///		&lt;xsd:restri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParametersXSD {
            get {
                return ResourceManager.GetString("ParametersXSD", resourceCulture);
            }
        }
    }
}
