ALTER TABLE [dbo].[Audit]
    ADD CONSTRAINT [AuditPK] PRIMARY KEY CLUSTERED ([AuditId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

